name: Deploy website
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      file-script: ${{ steps.publish.outputs.file-script }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: publish js file name 
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'file-script={}'>> $GITHUB_OUTPUT ';'
      - name: uploade artifact 
        uses: actions/upload-artifact@v4
        with: 
          name: dist-file
          path: dist
            

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: get build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-file
      - name: output contents
        run: ls 
      
      - name: ouput file name 
        run: echo "${{ needs.build.outputs.file-script }}"
      

      - name: Deploy
        run: echo "Deploying..."
